version: "3.4"

services:
    project:
        image: project-test
        ports:
            - "8000:8000"
        restart: always
        build:
            context: .
            dockerfile: Dockerfile
