// Code generated by go-swagger; DO NOT EDIT.

// Package restapi API Title
//
//  Schemes:
//    https
//  Host: 127.0.0.1:8000
//  BasePath: /api
//  Version: 1.0
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - application/json
//
// swagger:meta
package restapi
