// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	"ntq.project/project.test/models"
)

// NewPostUserParams creates a new PostUserParams object
// no default values defined in spec.
func NewPostUserParams() PostUserParams {

	return PostUserParams{}
}

// PostUserParams contains all the bound params for the post user operation
// typically these are obtained from a http.Request
//
// swagger:parameters postUser
type PostUserParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*New users to add
	  Required: true
	  In: body
	*/
	Users []*models.CommonUser
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewPostUserParams() beforehand.
func (o *PostUserParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body []*models.CommonUser
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("users", "body", ""))
			} else {
				res = append(res, errors.NewParseError("users", "body", "", err))
			}
		} else {
			// validate array of body objects
			for i := range body {
				if body[i] == nil {
					continue
				}
				if err := body[i].Validate(route.Formats); err != nil {
					res = append(res, err)
					break
				}
			}
			if len(res) == 0 {
				o.Users = body
			}
		}
	} else {
		res = append(res, errors.Required("users", "body", ""))
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
