// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"ntq.project/project.test/models"
)

// PutUserHandlerFunc turns a function with the right signature into a put user handler
type PutUserHandlerFunc func(PutUserParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PutUserHandlerFunc) Handle(params PutUserParams) middleware.Responder {
	return fn(params)
}

// PutUserHandler interface for that can handle valid put user params
type PutUserHandler interface {
	Handle(PutUserParams) middleware.Responder
}

// NewPutUser creates a new http.Handler for the put user operation
func NewPutUser(ctx *middleware.Context, handler PutUserHandler) *PutUser {
	return &PutUser{Context: ctx, Handler: handler}
}

/*PutUser swagger:route PUT /common/user common/user putUser

put users

put users

*/
type PutUser struct {
	Context *middleware.Context
	Handler PutUserHandler
}

func (o *PutUser) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPutUserParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}

// PutUserBody put user body
//
// swagger:model PutUserBody
type PutUserBody struct {

	// ids
	Ids []string `json:"ids"`

	// users
	Users []*models.CommonUser `json:"users"`
}

// Validate validates this put user body
func (o *PutUserBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateUsers(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *PutUserBody) validateUsers(formats strfmt.Registry) error {

	if swag.IsZero(o.Users) { // not required
		return nil
	}

	for i := 0; i < len(o.Users); i++ {
		if swag.IsZero(o.Users[i]) { // not required
			continue
		}

		if o.Users[i] != nil {
			if err := o.Users[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("task" + "." + "users" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (o *PutUserBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PutUserBody) UnmarshalBinary(b []byte) error {
	var res PutUserBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
